/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './app/__root'
import { Route as LayoutImport } from './app/_layout'
import { Route as publicIndexImport } from './app/(public)/index'
import { Route as featuresLayoutWarehousesIndexImport } from './app/(features)/_layout.warehouses/index'
import { Route as featuresLayoutDashboardIndexImport } from './app/(features)/_layout.dashboard/index'
import { Route as authLayoutLoginIndexImport } from './app/(auth)/_layout.login/index'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const publicIndexRoute = publicIndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const featuresLayoutWarehousesIndexRoute =
  featuresLayoutWarehousesIndexImport.update({
    path: '/warehouses/',
    getParentRoute: () => rootRoute,
  } as any)

const featuresLayoutDashboardIndexRoute =
  featuresLayoutDashboardIndexImport.update({
    path: '/dashboard/',
    getParentRoute: () => rootRoute,
  } as any)

const authLayoutLoginIndexRoute = authLayoutLoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/(public)/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/_layout/login/': {
      id: '/_layout/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLayoutLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/(features)/_layout/dashboard/': {
      id: '/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof featuresLayoutDashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/(features)/_layout/warehouses/': {
      id: '/_layout/warehouses/'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof featuresLayoutWarehousesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  publicIndexRoute,
  authLayoutLoginIndexRoute,
  featuresLayoutDashboardIndexRoute,
  featuresLayoutWarehousesIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/",
        "/_layout/login/",
        "/_layout/dashboard/",
        "/_layout/warehouses/"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx"
    },
    "/": {
      "filePath": "(public)/index.tsx"
    },
    "/_layout/login/": {
      "filePath": "(auth)/_layout.login/index.tsx"
    },
    "/_layout/dashboard/": {
      "filePath": "(features)/_layout.dashboard/index.tsx"
    },
    "/_layout/warehouses/": {
      "filePath": "(features)/_layout.warehouses/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
