name: Deploy app to Windows Server (Self-hosted)

on:
   push:
      branches:
         - develop
   pull_request:
      branches:
         - develop
   workflow_dispatch:

jobs:
   sonarcloud:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
           with:
              fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
         - name: Analyze with SonarCloud
           uses: SonarSource/sonarcloud-github-action@master
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

   test:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Set up Node.js
           uses: actions/setup-node@v4
           with:
              node-version: '20.x'
              cache: npm

         - name: Install dependencies
           run: npm ci

         - name: Unit testing
           run: npm run test

   deploy:
      runs-on: self-hosted
      needs: test
      steps:
         - name: Delete previous deployment
           shell: bash
           run: pm2 delete ecosystem.config.cjs || echo "Previous deployment not found. Skipping deletion."

         - name: Checkout code
           uses: actions/checkout@v4

         - name: Load environment variables
           shell: bash
           run: |
              echo "${{ secrets.ENV_VARIABLE }}" > .env.production
              ls

         - name: Set up Node.js
           uses: actions/setup-node@v4
           with:
              node-version: '20.x'
              cache: npm

         - name: Install dependencies
           run: npm ci

         - name: Generate PWA assets
           run: npm run generate-pwa-assets

         - name: Build the React app
           shell: bash
           run: npm run build

         - name: Restart PM2 process
           shell: bash
           run: pm2 start ecosystem.config.cjs
