name: Deploy React App to Windows Server with PM2

on:
   push:
      branches:
         - main

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Set up Node.js
           uses: actions/setup-node@v3
           with:
              node-version: '16'

         - name: Install dependencies
           run: npm install

         - name: Build the React app
           run: npm run build

         - name: Archive production artifacts
           uses: actions/upload-artifact@v3
           with:
              name: build-artifacts
              path: build

   deploy:
      runs-on: ubuntu-latest
      needs: build

      steps:
         - name: Download build artifacts
           uses: actions/download-artifact@v3
           with:
              name: build-artifacts
              path: build

         - name: Deploy to Windows Server
           uses: appleboy/scp-action@v0.1.1
           with:
              host: 10.30.0.19
              username: ${{ secrets.YOUR_WINDOWS_SERVER_USERNAME }}
              password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
              source: 'dist/*'
              target: 'C:/Users/Administrator/i-wms/client'

         - name: Restart PM2 process
           run: |
              sshpass -p ${{ secrets.WINDOWS_SERVER_PASSWORD }} ssh ${{ secrets.YOUR_WINDOWS_SERVER_USERNAME }}@10.30.0.19 `
              "cd C:/Users/Administrator/i-wms/client && pm2 restart 'wms-client'"
