name: Deploy app to Windows Server (Self-hosted)

on:
   push:
      branches:
         - develop
   pull_request:
      branches:
         - develop
   workflow_dispatch:

jobs:
   sonarcloud:
      name: SonarCloud
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
           with:
              fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
         - name: Analyze with SonarCloud
           uses: SonarSource/sonarcloud-github-action@master
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

   test:
      name: Test
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Install pnpm
           uses: pnpm/action-setup@v4
           with:
              version: 10

         - name: Set up Node.js
           uses: actions/setup-node@v4
           with:
              node-version: '23.x'
              cache: pnpm

         - name: Install dependencies
           run: pnpm install

         - name: Unit testing
           run: pnpm test

   deploy-server-19:
      name: Deploy to server 0.19
      runs-on: [self-hosted, Server-19]
      needs: test
      steps:
         - name: Checkout code
           uses: actions/checkout@v4
           with:
              fetch-depth: 0
              clean: false

         - name: Load environment variables
           shell: bash
           run: echo "${{ secrets.ENV_VARIABLE_SVR19 }}" > .env.production

         - name: Install dependencies
           shell: bash
           run: pnpm install --fix-lockfile

         - name: Generate PWA assets
           shell: bash
           run: pnpm generate-pwa-assets

         - name: Build the React app
           shell: bash
           run: pnpm build

         - name: Restart and save PM2 process
           shell: bash
           run: |
              pm2 restart ecosystem.config.cjs
              pm2 save

   deploy-server-201:
      name: Deploy to server 201.201
      runs-on: [self-hosted, Server-201201]
      needs: test
      steps:
         - name: Checkout code
           uses: actions/checkout@v4
           with:
              fetch-depth: 0
              clean: false

         - name: Load environment variables
           shell: bash
           run: echo "${{ secrets.ENV_VARIABLE_SVR201201 }}" > .env.production

         - name: Install dependencies
           shell: bash
           run: pnpm install --fix-lockfile

         - name: Generate PWA assets
           shell: bash
           run: pnpm generate-pwa-assets

         - name: Build the React app
           shell: bash
           run: pnpm build

         - name: Restart and save PM2 process
           shell: bash
           run: |
              pm2 restart ecosystem.config.cjs
              pm2 save

   deploy-server-5251:
      name: Deploy to server 5.251
      runs-on: [self-hosted, Server-5251]
      needs: test
      steps:
         - name: Checkout code
           uses: actions/checkout@v4
           with:
              fetch-depth: 0
              clean: false

         - name: Load environment variables
           shell: bash
           run: echo "${{ secrets.ENV_VARIABLE_SVR5251 }}" > .env.production

         - name: Install dependencies
           shell: bash
           run: pnpm install --fix-lockfile

         - name: Generate PWA assets
           shell: bash
           run: pnpm generate-pwa-assets

         - name: Build the React app
           shell: bash
           run: pnpm build

         - name: Restart and save PM2 process
           shell: bash
           run: |
              pm2 restart ecosystem.config.cjs
              pm2 save
