on:
   push:
      branches:
         - dev

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: 20.9.0
         - run: npm ci
         - run: npm run build
         - name: Deploy to production
           uses: appleboy/ssh-action@dev
           with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              password: ${{ secrets.PASSWORD }}
              script: |
                 cd C:/Users/Administrator/fe-wms
                 git pull origin dev
                 npm install && npm run build
                 pm2 reload all
